 export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
 export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
 export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

 export const PRODUCT_DETAIlS_REQUEST = 'PRODUCT_DETAIlS_REQUEST'
 export const PRODUCT_DETAIlS_SUCCESS = 'PRODUCT_DETAIlS_SUCCESS'
 export const PRODUCT_DETAIlS_FAIL = 'PRODUCT_DETAIlS_FAIL'