 export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
 export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
 export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

 export const PRODUCT_DETAIlS_REQUEST = 'PRODUCT_DETAIlS_REQUEST'
 export const PRODUCT_DETAIlS_SUCCESS = 'PRODUCT_DETAIlS_SUCCESS'
 export const PRODUCT_DETAIlS_FAIL = 'PRODUCT_DETAIlS_FAIL'

 export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
 export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
 export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

 export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
 export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
 export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
 export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'
